### ISSUE TITLE
Float64() fails when the input is 0.0

### ISSUE THREAD

**Issue by nvx** [valyala/fastjson#18]
When calling Float64(), if the json value is 0.0 it fails to parse. When the value is 0 however it works.

It looks like the issue is this line here: https://github.com/valyala/fastjson/blob/b6e48611043ed08d52618fec2a9653549cac929a/parser.go#L818

That line checks for the literal value of "0", but not for "0.0". Semantically 0.00 should also behave the same. Perhaps fastfloat.ParseBestEffort should return an explicit error that can be checked rather than relying on the sentinel value of 0?

**Comment by valyala** [comment]
Fixed the issue by just removing the condition on the `line 818`. Now `Float64` should properly parse zero values. `Float64` may return `0, nil` for invalid floating point numbers such as `1.23.45`, but it is OK for now, since such numbers are rare in real life. I'll try resolving this in the next CLs.
